import React from 'react';
import { Card, Row, Col, Table, Typography } from 'antd';
import BasicButton from './BasicButton';
import SearchButton from './SearchButton';
import { dataSource, columns } from './ButtonDoc';

const { Title, Text } = Typography;

const ButtonExample = () => {
    return (
        <>
            <Row gutter={[6, 6]}>
                <Col span={8}>
                    <Card title="Basic Button" bordered={true}>
                        <BasicButton />
                    </Card>
                </Col>
                <Col span={8}>
                    <Card title="Search Button" bordered={true}>
                        <SearchButton />
                    </Card>
                </Col>
                <Col span={8}>
                    <Card title="Card title" bordered={true}>
                        <BasicButton />
                    </Card>
                </Col>

                <Col span={24}>
                    <Title level={4} style={{ marginTop: 40 }}>Button</Title>
                    <Text>Different button styles can be generated by setting Button properties. The recommended order is: type -&gt; shape -&gt; size -&gt; loading -&gt; disabled.</Text>
                    <Table dataSource={dataSource} columns={columns} pagination={false} />
                </Col>
            </Row>
        </>
    );
};

export default ButtonExample;