import React from 'react';
import { Card, Row, Col, Table, Typography } from 'antd';
import { dataSource, columns } from './TableDoc'

const { Title, Text } = Typography;

const TableExample = () => {
  return (
    <div>
      <Row gutter={[6, 6]}>
        <Col span={24}>
          <Title level={3}>API</Title>
          <Text>Different button styles can be generated by setting Button properties. The recommended order is: type -&gt; shape -&gt; size -&gt; loading -&gt; disabled.</Text>
          <Table dataSource={dataSource} columns={columns} pagination={false} />
        </Col>

      </Row>

    </div>
  );
};

export default TableExample;