import React from 'react';
import { Card, Row, Col, Table, Typography } from 'antd';
import { dataSource, dataSource2, dataSource3, columns } from './CardDoc'

const { Title, Text } = Typography;

const CardExample = () => {
  return (
    <div>
      <Row gutter={[6, 6]}>
        <Col span={24}>
          <Title level={4} style={{ marginTop: 40 }}>Button</Title>
          <Text>Different button styles can be generated by setting Button properties. The recommended order is: type -&gt; shape -&gt; size -&gt; loading -&gt; disabled.</Text>
          <Table dataSource={dataSource} columns={columns} pagination={false} />
        </Col>
        <Col span={24}>
          <Title level={4} style={{ marginTop: 40 }}>Button</Title>
          <Text>Different button styles can be generated by setting Button properties. The recommended order is: type -&gt; shape -&gt; size -&gt; loading -&gt; disabled.</Text>
          <Table dataSource={dataSource2} columns={columns} pagination={false} />
        </Col>
        <Col span={24}>
          <Title level={4} style={{ marginTop: 40 }}>Button</Title>
          <Text>Different button styles can be generated by setting Button properties. The recommended order is: type -&gt; shape -&gt; size -&gt; loading -&gt; disabled.</Text>
          <Table dataSource={dataSource3} columns={columns} pagination={false} />
        </Col>

      </Row>

    </div>
  );
};

export default CardExample;